// <auto-generated />
namespace Consumer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Score : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Score));
        
        string IMigrationMetadata.Id
        {
            get { return "201211180030558_Score"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
