IF NOT EXISTS (SELECT TOP 1 * FROM [dbo].[States])
BEGIN
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'AK', N'Alaska')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'AL', N'Alabama')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'AR', N'Arkansas')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'AZ', N'Arizona')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'CA', N'California')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'CO', N'Colorado')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'CT', N'Connecticut')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'DC', N'District of Columbia')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'DE', N'Delaware')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'FL', N'Florida')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'GA', N'Georgia')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'HI', N'Hawaii')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'IA', N'Iowa')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'ID', N'Idaho')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'IL', N'Illinois')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'IN', N'Indiana')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'KS', N'Kansas')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'KY', N'Kentucky')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'LA', N'Louisiana')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'MA', N'Massachusetts')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'MD', N'Maryland')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'ME', N'Maine')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'MI', N'Michigan')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'MN', N'Minnesota')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'MO', N'Missouri')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'MS', N'Mississippi')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'MT', N'Montana')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'NC', N'North Carolina')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'ND', N'North Dakota')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'NE', N'Nebraska')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'NH', N'New Hampshire')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'NJ', N'New Jersey')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'NM', N'New Mexico')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'NV', N'Nevada')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'NY', N'New York')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'OH', N'Ohio')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'OK', N'Oklahoma')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'OR', N'Oregon')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'PA', N'Pennsylvania')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'RI', N'Rhode Island')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'SC', N'South Carolina')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'SD', N'South Dakota')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'TN', N'Tennessee')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'TX', N'Texas')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'UT', N'Utah')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'VA', N'Virginia')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'VT', N'Vermont')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'WA', N'Washington')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'WI', N'Wisconsin')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'WV', N'West Virginia')
INSERT INTO [dbo].[States] ([StateId], [Name]) VALUES (N'WY', N'Wyoming')
END